ladieslearningcode/llc-html-css-multi-page-site

- slides.html
> typos slide 31

- slides.html
Mostly grammar and spelling fixes.
> Proofreading

- slides.html
Reference:
http://caniuse.com/#search=flexbox
> Remove outdated statement regarding Flexbox

- slides.html
- Removed "logo" from `alt` text
- Added `ul` for wifi content
- Added `download` attribute to zip file link
- Wrapped `index.html` filename with semantic `code` element
- Removed protocol from visible link text; easier to read/understand
- Wrapped arrow icons with `aria-hidden` for screen reader exclusion
> Slide 1 updates

- slides.html
> Slide 8 updates

- slides.html
- Added list for semantic structure and consistency
> Slide 10 updates

- slides.html
- Added links to browsers
- Added list(s) for semantic structure and consistency
> Slide 12 updates

- slides.html
- Added list(s) for semantic structure and consistency
- Removed broken link
> Slide 14 updates

- slides.html
- Added list(s) for semantic structure and consistency
> Slide 15 updates

- slides.html
> Slide 16 updates

- slides.html
> Slide 17 updates

- slides.html
> Slide 18 updates

- slides.html
- Wrapped keystrokes with semantic `kbd` element
> Slide 19 updates

- slides.html
- Wrapped keystrokes with semantic `kbd` element
> Slide 21 updates

- slides.html
- Wrapped keystrokes with semantic `kbd` element
> Slide 22 updates

- slides.html
> Slide 23 updates

- slides.html
> Slide 24 updates

- slides.html
> Slide 26 updates

- slides.html
> Slide 34 updates

- slides.html
> Slide 35 updates

- slides.html
> Slide 36 updates

- slides.html
> Slide 37 updates

- slides.html
> Slide 45 updates

- slides.html
> Slide 46 updates

- slides.html
> Slide 47 updates

- slides.html
> Slide 48 updates

- slides.html
- Wrapped keystrokes with semantic `kbd` element
> Slide 49 updates

- slides.html
> Slide 50 updates

- slides.html
> Slide 51 updates

- slides.html
- Added list
- Wrapped file types with semantic `code` element
> Slide 52 updates

- slides.html
> Slide 53 updates

- slides.html
> Slide 55 updates

- slides.html
Hello,
The URL to Beautiful Web Type has changed. The previous domain was purchased by a spammer who is using it to link to their essay writing services. The new URL also contains a much improved version of the project. Thanks!
> Update URL to Beautiful Web Type
